In [1]:
!cd /home/kamil.kural/FdaPrecision Challenge

/usr/bin/sh: line 0: cd: /home/kamil.kural/FdaPrecision: No such file or directory


In [2]:
import os
current_path = os.getcwd()

In [3]:
current_path

'/home/kamil.kural/FdaPrecision Challenge'

In [4]:
import numpy as np
import pandas as pd
import os
import copy
import matplotlib.pyplot as plt
%matplotlib inline
from tqdm import tqdm_notebook
from sklearn.preprocessing import StandardScaler
from sklearn.svm import NuSVR, SVR
from sklearn.metrics import mean_absolute_error
pd.options.display.precision = 15
from collections import defaultdict
import lightgbm as lgb
import xgboost as xgb
import catboost as cat
import time
import datetime
from catboost import CatBoostRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold, KFold, RepeatedKFold, GroupKFold, GridSearchCV, train_test_split, TimeSeriesSplit, RepeatedStratifiedKFold
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import linear_model
import gc
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import eli5
import shap
from IPython.display import HTML
import json
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline
from typing import List

import os
import time
import datetime
import json
import gc
from numba import jit

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm_notebook

import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor, CatBoostClassifier
from sklearn import metrics
from typing import Any
from itertools import product
pd.set_option('max_rows', 500)
import re
from tqdm import tqdm
from joblib import Parallel, delayed

Using TensorFlow backend.


In [5]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier,VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from IPython.display import display
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.tree import export_graphviz
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import GridSearchCV
import torch 
import fastai
import bayes_opt

In [112]:
from sklearn.tree import export_graphviz
import xgboost
import lightgbm
from sklearn.metrics import roc_auc_score

In [7]:
df1=pd.read_csv ('/home/kamil.kural/FdaPrecision Challenge/sc2_Phase1_CN_FeatureMatrix.tsv', sep='\t')

In [8]:
df2=pd.read_csv ('/home/kamil.kural/FdaPrecision Challenge/sc2_Phase1_CN_Outcome.tsv', sep='\t')

In [9]:
df3=pd.read_csv ('/home/kamil.kural/FdaPrecision Challenge/sc2_Phase1_CN_Phenotype.tsv', sep='\t')

In [10]:
df = pd.merge(df2,
                    df1,
                    left_index=True,
                    right_index=True)
df = pd.merge(df,
                    df3,
                    left_index=True,
                    right_index=True)

In [11]:
df=df.drop(['PATIENTID','PATIENTID_x','PATIENTID_y'], axis=1)

In [12]:
dfnew= df[['11p15.4', 'RACE','9p24.1' ,'12p13.33', '9p21.3', 'SEX', '4q21.21' ,'20q11.21']]

In [13]:
df=pd.get_dummies(df)

In [14]:
all_features = [x for x in df.columns if x not in ['SURVIVAL_STATUS']]

In [15]:
X, y = df[all_features], df['SURVIVAL_STATUS']
labelencoder_y_1 = LabelEncoder()
y = labelencoder_y_1.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0])

In [16]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
X = scaler.fit_transform(X)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42,stratify=df['SURVIVAL_STATUS'])

In [18]:
from bayes_opt import BayesianOptimization
from sklearn.model_selection import cross_val_score

In [23]:
pbounds = {
    'learning_rate': (0.01, 1.0),
    'n_estimators': (100,200),
    'max_depth': (15,25),
    'subsample': (0.1, 1.0),  # Change for big datasets
    'colsample': (0.1, 1.0),  # Change for datasets with lots of features
    'gamma': (0, 5),
    'max_delta_step' : (0,5),
    'min_child_weight' : (0,5),
    'reg_alpha' : (0.1, 1),
    'reg_lambda' : (0.1,1),
    'scale_pos_weight' : (0.1, 1)}
 
def xgboost_hyper_param(learning_rate,
                        n_estimators,
                        max_depth,
                        subsample,
                        colsample,
                        gamma,
                        max_delta_step,
                        min_child_weight,
                        reg_alpha,
                        reg_lambda,
                        scale_pos_weight):
 
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
 
    clf = XGBClassifier(
        max_depth=max_depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        gamma=gamma,
        max_delta_step=max_delta_step,
        min_child_weight=min_child_weight,
        reg_lambda=reg_lambda,
        reg_alpha=reg_alpha,
        scale_pos_weight=scale_pos_weight)
    return np.mean(cross_val_score(clf, X_train, y_train, cv=5, scoring='accuracy',n_jobs=50))
 
 
optimizer = BayesianOptimization(
    f=xgboost_hyper_param,
    pbounds=pbounds,
    random_state=1)

In [24]:
optimizer.maximize(init_points=10, n_iter=20, acq='ei')

|   iter    |  target   | colsample |   gamma   | learni... | max_de... | max_depth | min_ch... | n_esti... | reg_alpha | reg_la... | scale_... | subsample |
-------------------------------------------------------------------------------------------------------------------------------------------------------------
|  1        |  0.7198   |  0.4753   |  3.602    |  0.01011  |  1.512    |  16.47    |  0.4617   |  118.6    |  0.411    |  0.4571   |  0.5849   |  0.4773   |
|  2        |  0.7341   |  0.7167   |  1.022    |  0.8793   |  0.1369   |  21.7     |  2.087    |  155.9    |  0.2263   |  0.2783   |  0.8207   |  0.9714   |
|  3        |  0.6407   |  0.3821   |  3.462    |  0.8776   |  4.473    |  15.85    |  0.1953   |  117.0    |  0.8903   |  0.1885   |  0.479    |  0.9621   |
|  4        |  0.568    |  0.5798   |  3.459    |  0.3224   |  3.433    |  23.35    |  0.09144  |  175.0    |  0.99     |  0.7733   |  0.3524   |  0.8104   |
|  5        |  0.6481   |  0.1929   |  2.239    |  0

KeyboardInterrupt: 

In [25]:
optimizer.max

{'target': 0.7486772486772486,
 'params': {'colsample': 0.6970973480366033,
  'gamma': 3.1084786010456087,
  'learning_rate': 0.12359851322384142,
  'max_delta_step': 4.747446293535356,
  'max_depth': 19.499121334799405,
  'min_child_weight': 2.891948071935659,
  'n_estimators': 140.8136802761281,
  'reg_alpha': 0.31332428221872494,
  'reg_lambda': 0.9130415685060284,
  'scale_pos_weight': 0.6163115380050572,
  'subsample': 0.10258329432804308}}

In [39]:
model1=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.01, max_delta_step=5, max_depth=20,
              min_child_weight=5, missing=None, n_estimators=200, n_jobs=20,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0.1, reg_lambda=1, scale_pos_weight=0.4, seed=None,
              silent=None, subsample=1, class_weight='balanced')

In [40]:
eval_set = [(X_train, y_train), (X_test, y_test)]
eval_metric = ["auc","error"]
%time model1.fit(X_train,y_train,eval_metric =eval_metric, eval_set=eval_set)

[0]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[1]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[2]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[3]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[4]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[5]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[6]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[7]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[8]	validation_0-auc:0.786555	validation_0-error:0.230216	validation_1-auc:0.576923	validation_1-error:0

XGBClassifier(base_score=0.5, booster='gbtree', class_weight='balanced',
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              gamma=0, learning_rate=0.01, max_delta_step=5, max_depth=20,
              min_child_weight=5, missing=None, n_estimators=200, n_jobs=20,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0.1, reg_lambda=1, scale_pos_weight=0.4, seed=None,
              silent=None, subsample=1, verbosity=1)

In [41]:
pred=model1.predict(X)

In [42]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.6976744186046512
Sensitivity :  0.9007633587786259
Accuracy :  0.8505747126436781
Confusion Matrix : 
 [ 30  13  13 118]


In [45]:
from sklearn.ensemble import RandomForestClassifier
pbounds = {
    
    'n_estimators': (100,500),
    'max_depth': (20, 500),  # Change for big datasets
    'min_samples_split': (0.1, 1),  # Change for datasets with lots of features
                                }
 
def rf_hyper_param(
                        n_estimators,
                        max_depth,
                        min_samples_split,
                        
                        ):
 
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
 
    clf = RandomForestClassifier(
        max_depth=max_depth,
        n_estimators=n_estimators,
        min_samples_split=min_samples_split,
        
        )
    return np.mean(cross_val_score(clf, X_train, y_train, cv=5, scoring='accuracy',n_jobs=50))
 
 
optimizer = BayesianOptimization(
    f=rf_hyper_param,
    pbounds=pbounds,
    random_state=1)

In [46]:
optimizer.maximize(init_points=10, n_iter=20, acq='ei')

|   iter    |  target   | max_depth | min_sa... | n_esti... |
-------------------------------------------------------------
|  1        |  0.7556   |  220.2    |  0.7483   |  100.0    |
|  2        |  0.741    |  165.1    |  0.2321   |  136.9    |
|  3        |  0.7556   |  109.4    |  0.411    |  258.7    |
|  4        |  0.7484   |  278.6    |  0.4773   |  374.1    |
|  5        |  0.7556   |  118.1    |  0.8903   |  111.0    |
|  6        |  0.7556   |  341.8    |  0.4756   |  323.5    |
|  7        |  0.7339   |  87.39    |  0.2783   |  420.3    |
|  8        |  0.7484   |  484.8    |  0.3821   |  376.9    |
|  9        |  0.7556   |  440.7    |  0.9051   |  134.0    |
|  10       |  0.7267   |  38.75    |  0.2528   |  451.3    |
|  11       |  0.7556   |  20.0     |  1.0      |  100.0    |
|  12       |  0.7556   |  20.6     |  0.8851   |  288.4    |
|  13       |  0.7556   |  387.7    |  0.8196   |  100.0    |
|  14       |  0.741    |  499.3    |  0.291    |  100.2    |
|  15   

In [47]:
randomforest = RandomForestClassifier(criterion='gini',n_estimators=400,max_depth=350,min_samples_split=0.1,min_impurity_decrease=0.0,min_weight_fraction_leaf=0.05,max_features='auto', min_samples_leaf=7,random_state=0,oob_score=True,class_weight='balanced_subsample')

In [48]:
randomforest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced_subsample',
                       criterion='gini', max_depth=350, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=7,
                       min_samples_split=0.1, min_weight_fraction_leaf=0.05,
                       n_estimators=400, n_jobs=None, oob_score=True,
                       random_state=0, verbose=0, warm_start=False)

In [49]:
pred=randomforest.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.7906976744186046
Sensitivity :  0.9618320610687023
Accuracy :  0.9195402298850575
Confusion Matrix : 
 [ 34   9   5 126]


In [50]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000] }
clf = GridSearchCV(LogisticRegression(penalty='l2'), param_grid)
GridSearchCV(cv=5,
             estimator=LogisticRegression(C=1.0, intercept_scaling=1, class_weight='balanced' ,
               dual=False, fit_intercept=True, penalty='l2', tol=0.0001,n_jobs=50,verbose= 1000),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]})

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight='balanced',
                                          dual=False, fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=50, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=1000,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [51]:
clf.fit(X_train,y_train)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [52]:
best_params = clf.best_params_
best_params

{'C': 0.1}

In [62]:
lr1=LogisticRegression(C=0.01, class_weight='balanced', dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=300, multi_class='ovr',
                                          n_jobs=20, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=1e-4, verbose=1,
                                          warm_start=False)

In [63]:
lr1.fit(X_train,y_train)

[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.6s finished


LogisticRegression(C=0.01, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=300, multi_class='ovr', n_jobs=20, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=1,
                   warm_start=False)

In [64]:
pred=lr1.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.813953488372093
Sensitivity :  0.9618320610687023
Accuracy :  0.9252873563218391
Confusion Matrix : 
 [ 35   8   5 126]


In [65]:
def lgb_eval(num_leaves, feature_fraction, bagging_fraction, max_depth, lambda_l1, lambda_l2, min_split_gain, min_child_weight):
    params = {'application':'binary','num_iterations':300, 'learning_rate':0.05, 'early_stopping_round':100, 'metric':'auc'}
    params["num_leaves"] = round(num_leaves)
    params['feature_fraction'] = max(min(feature_fraction, 1), 0)
    params['bagging_fraction'] = max(min(bagging_fraction, 1), 0)
    params['max_depth'] = round(max_depth)
    params['lambda_l1'] = max(lambda_l1, 0)
    params['lambda_l2'] = max(lambda_l2, 0)
    params['min_split_gain'] = min_split_gain
    params['min_child_weight'] = min_child_weight
    cv_result = lgb.cv(params, train_data, nfold=n_folds, seed=random_seed, stratified=True, verbose_eval =200, metrics=['auc'])
    return max(cv_result['auc-mean'])

In [66]:
lgbBO = BayesianOptimization(lgb_eval, {'num_leaves': (24, 45),
                                        'feature_fraction': (0.1, 0.9),
                                        'bagging_fraction': (0.8, 1),
                                        'max_depth': (5, 8.99),
                                        'lambda_l1': (0, 5),
                                        'lambda_l2': (0, 3),
                                        'min_split_gain': (0.001, 0.1),
                                        'min_child_weight': (5, 50)}, random_state=0)

In [68]:
def bayes_parameter_opt_lgb(X_train, y_train, init_round=15, opt_round=25, n_folds=5, random_seed=0, n_estimators=10000, learning_rate=0.05, output_process=False):
    # prepare data
    train_data = lgb.Dataset(data=X_train, label=y_train)
    # parameters
    def lgb_eval(num_leaves, feature_fraction, bagging_fraction, max_depth, lambda_l1, lambda_l2, min_split_gain, min_child_weight,n_jobs=20):
        params = {'application':'binary','num_iterations': n_estimators, 'learning_rate':learning_rate, 'early_stopping_round':100, 'metric':'auc'}
        params["num_leaves"] = int(round(num_leaves))
        params['feature_fraction'] = max(min(feature_fraction, 1), 0)
        params['bagging_fraction'] = max(min(bagging_fraction, 1), 0)
        params['max_depth'] = int(round(max_depth))
        params['lambda_l1'] = max(lambda_l1, 0)
        params['lambda_l2'] = max(lambda_l2, 0)
        params['min_split_gain'] = min_split_gain
        params['min_child_weight'] = min_child_weight
        cv_result = lgb.cv(params, train_data, nfold=n_folds, seed=random_seed, stratified=True, verbose_eval =200, metrics=['auc'])
        return max(cv_result['auc-mean'])
    # range 
    lgbBO = BayesianOptimization(lgb_eval, {'num_leaves': (24, 45),
                                            'feature_fraction': (0.1, 0.9),
                                            'bagging_fraction': (0.8, 1),
                                            'max_depth': (5, 25),
                                            'lambda_l1': (0, 5),
                                            'lambda_l2': (0, 3),
                                            'min_split_gain': (0.001, 0.1),
                                            'min_child_weight': (1, 10)}, random_state=0)
    # optimize
    lgbBO.maximize(init_points=init_round, n_iter=opt_round)
    
    # output optimization process
    if output_process==True: lgbBO.points_to_csv("bayes_opt_result.csv")
    
    # return best parameters
    

opt_params = bayes_parameter_opt_lgb(X, y, init_round=10, opt_round=20, n_folds=5, random_seed=0, n_estimators=100, learning_rate=0.01)

|   iter    |  target   | baggin... | featur... | lambda_l1 | lambda_l2 | max_depth | min_ch... | min_sp... | num_le... |
-------------------------------------------------------------------------------------------------------------------------
|  1        |  0.5137   |  0.9098   |  0.6722   |  3.014    |  1.635    |  13.47    |  6.813    |  0.04432  |  42.73    |
|  2        |  0.575    |  0.9927   |  0.4068   |  3.959    |  1.587    |  16.36    |  9.33     |  0.008033 |  25.83    |
|  3        |  0.5216   |  0.804    |  0.7661   |  3.891    |  2.61     |  24.57    |  8.192    |  0.04669  |  40.39    |
|  4        |  0.5774   |  0.8237   |  0.6119   |  0.7168   |  2.834    |  15.44    |  4.732    |  0.02719  |  40.26    |
|  5        |  0.5451   |  0.8912   |  0.5547   |  0.09395  |  1.853    |  17.24    |  6.552    |  0.09443  |  38.32    |
|  6        |  0.5149   |  0.8719   |  0.4496   |  3.488    |  0.1807   |  18.34    |  7.036    |  0.02183  |  26.71    |
|  7        |  0.5905   

In [90]:
from lightgbm import LGBMClassifier
model2=LGBMClassifier(num_leaves= 45, feature_fraction= 0.9, learning_rate= 0.01, bagging_fraction= 1, max_depth= 5,scale_pos_weight=0.3, min_child_weight= 1, n_estimators= 200, lambda_l1= 0, lambda_l2= 0, min_split_gain=0.001, n_jobs= 20, verbose=1)

In [91]:
model2.fit(X_train,y_train,eval_metric =eval_metric, eval_set=eval_set, verbose=100)

[100]	valid_0's auc: 0.991176	valid_0's binary_logloss: 0.357877	valid_1's auc: 0.717949	valid_1's binary_logloss: 0.522947
[200]	valid_0's auc: 0.997759	valid_0's binary_logloss: 0.261502	valid_1's auc: 0.692308	valid_1's binary_logloss: 0.55657


LGBMClassifier(bagging_fraction=1, boosting_type='gbdt', class_weight=None,
               colsample_bytree=1.0, feature_fraction=0.9,
               importance_type='split', lambda_l1=0, lambda_l2=0,
               learning_rate=0.01, max_depth=5, min_child_samples=20,
               min_child_weight=1, min_split_gain=0.001, n_estimators=200,
               n_jobs=20, num_leaves=45, objective=None, random_state=None,
               reg_alpha=0.0, reg_lambda=0.0, scale_pos_weight=0.3, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0,
               verbose=1)

In [92]:
pred=model2.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.8837209302325582
Sensitivity :  0.9312977099236641
Accuracy :  0.9195402298850575
Confusion Matrix : 
 [ 38   5   9 122]


In [93]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84        43
           1       0.96      0.93      0.95       131

    accuracy                           0.92       174
   macro avg       0.88      0.91      0.90       174
weighted avg       0.92      0.92      0.92       174



In [128]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
#List Hyperparameters that we want to tune.
n_neighbors = list(range(1,50))
p=[1,2,3,4,5,6,7,8,9,10]
#Convert to dictionary
hyperparameters = dict( n_neighbors=n_neighbors, p=p)
#Create new KNN object
knn_2 = KNeighborsClassifier()
#Use GridSearch
clf = GridSearchCV(knn_2, hyperparameters, cv=10, n_jobs=50,verbose=1,scoring='roc_auc')
#Fit the model
best_model = clf.fit(X,y)
#Print The value of best Hyperparameters
print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
print('Best p:', best_model.best_estimator_.get_params()['p'])
print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])

Fitting 10 folds for each of 490 candidates, totalling 4900 fits


[Parallel(n_jobs=50)]: Using backend LokyBackend with 50 concurrent workers.
[Parallel(n_jobs=50)]: Done 100 tasks      | elapsed:    1.6s
[Parallel(n_jobs=50)]: Done 400 tasks      | elapsed:    2.3s
[Parallel(n_jobs=50)]: Done 1700 tasks      | elapsed:    5.0s
[Parallel(n_jobs=50)]: Done 3500 tasks      | elapsed:    8.6s


Best leaf_size: 30
Best p: 8
Best n_neighbors: 43


[Parallel(n_jobs=50)]: Done 4900 out of 4900 | elapsed:   11.5s finished


In [129]:
knn = KNeighborsClassifier(leaf_size=30, p=8, n_neighbors= 43,weights='distance')

In [130]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=43, p=8,
                     weights='distance')

In [131]:
pred=knn.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.7906976744186046
Sensitivity :  1.0
Accuracy :  0.9482758620689655
Confusion Matrix : 
 [ 34   9   0 131]


In [132]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.8953488372093023

In [133]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       1.00      0.79      0.88        43
           1       0.94      1.00      0.97       131

    accuracy                           0.95       174
   macro avg       0.97      0.90      0.92       174
weighted avg       0.95      0.95      0.95       174



In [100]:
from sklearn.linear_model import RidgeClassifier
develop = True
seed = 0

    
def target(**params):
    fit_intercept = int(params['fit_intercept'])
    fit_intercept_dict = {0:False, 1:True}

    model = RidgeClassifier(alpha = params['alpha'],
                    fit_intercept = fit_intercept_dict[fit_intercept],
                    copy_X = True,class_weight='balanced' )
    
    scores = cross_val_score(model, X, y, scoring='accuracy', cv=5)
    return scores.mean()
    
params = {'alpha':(1, 50),
          'fit_intercept':(0,1.99)}
if develop:
    bo = BayesianOptimization(target, params, random_state=seed)
    bo.maximize(init_points=5, n_iter=10, acq='ucb')
    

|   iter    |  target   |   alpha   | fit_in... |
-------------------------------------------------
|  1        |  0.5271   |  27.89    |  1.423    |
|  2        |  0.5271   |  30.54    |  1.084    |
|  3        |  0.5157   |  21.76    |  1.285    |
|  4        |  0.5157   |  22.44    |  1.775    |
|  5        |  0.2468   |  48.22    |  0.763    |
|  6        |  0.2355   |  1.0      |  0.0      |
|  7        |  0.2527   |  27.83    |  0.0      |
|  8        |  0.5098   |  11.4     |  1.99     |
|  9        |  0.5385   |  39.55    |  1.99     |
|  10       |  0.247    |  15.38    |  0.0      |
|  11       |  0.51     |  5.992    |  1.99     |
|  12       |  0.5328   |  34.93    |  1.99     |
|  13       |  0.2468   |  42.74    |  0.0      |
|  14       |  0.2528   |  8.17     |  0.0      |
|  15       |  0.5273   |  18.28    |  1.99     |


In [101]:
ridgemodel = RidgeClassifier(alpha = 39.55    ,
                  fit_intercept = 1.99, class_weight='balanced',
                  copy_X = True)

ridgemodel.fit(X_train, y_train)
pred = ridgemodel.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.7906976744186046
Sensitivity :  0.9923664122137404
Accuracy :  0.9425287356321839
Confusion Matrix : 
 [ 34   9   1 130]


In [157]:
from sklearn.ensemble import VotingClassifier

voting_classifier = VotingClassifier(estimators=[
    ('logreg',lr1), 
    ('random_forest', randomforest),
    ('lgb', model2),
    ('xgb',model1), 
    ('knn', knn)],voting='hard')
voting_classifier.fit(X_train,y_train)

[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.6s finished


VotingClassifier(estimators=[('logreg',
                              LogisticRegression(C=0.01,
                                                 class_weight='balanced',
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=300,
                                                 multi_class='ovr', n_jobs=20,
                                                 penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=1, warm_start=False)),
                             ('random_forest',
                              RandomForestClassifier(bootstrap=True,
                                                     class_weight='b...
                                            o

In [158]:
pred=voting_classifier.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.8604651162790697
Sensitivity :  0.9923664122137404
Accuracy :  0.9597701149425287
Confusion Matrix : 
 [ 37   6   1 130]


In [159]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.926415764246405

In [144]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       0.97      0.86      0.91        43
           1       0.96      0.99      0.97       131

    accuracy                           0.96       174
   macro avg       0.96      0.93      0.94       174
weighted avg       0.96      0.96      0.96       174



In [145]:
from mlxtend.classifier import StackingCVClassifier
lr = LogisticRegression(C=0.01)
sclf = StackingCVClassifier(classifiers = [lr1, randomforest, model1, knn],
                            shuffle = False,
                            use_probas = True,
                            cv = 5,
                            meta_classifier = lr1)

In [146]:
sclf.fit(X_train, y_train)

[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.6s finished
[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.6s finished
[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.6s finished
[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.6s finished
[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.6s finished
[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.7s finished
[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out

StackingCVClassifier(classifiers=[LogisticRegression(C=0.01,
                                                     class_weight='balanced',
                                                     dual=False,
                                                     fit_intercept=True,
                                                     intercept_scaling=1,
                                                     l1_ratio=None,
                                                     max_iter=300,
                                                     multi_class='ovr',
                                                     n_jobs=20, penalty='l2',
                                                     random_state=None,
                                                     solver='lbfgs', tol=0.0001,
                                                     verbose=1,
                                                     warm_start=False),
                                  RandomForestClassifier(bootstrap=True,
  

In [147]:
pred=sclf.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.9069767441860465
Sensitivity :  0.816793893129771
Accuracy :  0.8390804597701149
Confusion Matrix : 
 [ 39   4  24 107]


In [148]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.8618853186579088