In [385]:
!cd /home/kamil.kural/FdaPrecision Challenge

/usr/bin/sh: line 0: cd: /home/kamil.kural/FdaPrecision: No such file or directory


In [386]:
import os
current_path = os.getcwd()

In [387]:
current_path

'/home/kamil.kural/FdaPrecision Challenge'

In [388]:
import numpy as np
import pandas as pd
import os
import copy
import matplotlib.pyplot as plt
%matplotlib inline
from tqdm import tqdm_notebook
from sklearn.preprocessing import StandardScaler
from sklearn.svm import NuSVR, SVR
from sklearn.metrics import mean_absolute_error
pd.options.display.precision = 15
from collections import defaultdict
import lightgbm as lgb
import xgboost as xgb
import catboost as cat
import time
import datetime
from catboost import CatBoostRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold, KFold, RepeatedKFold, GroupKFold, GridSearchCV, train_test_split, TimeSeriesSplit, RepeatedStratifiedKFold
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import linear_model
import gc
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import eli5
import shap
from IPython.display import HTML
import json
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline
from typing import List

import os
import time
import datetime
import json
import gc
from numba import jit

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm_notebook

import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor, CatBoostClassifier
from sklearn import metrics
from typing import Any
from itertools import product
pd.set_option('max_rows', 500)
import re
from tqdm import tqdm
from joblib import Parallel, delayed

In [389]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier,VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from IPython.display import display
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.tree import export_graphviz
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import GridSearchCV
import torch 
import fastai
import bayes_opt

In [390]:
from sklearn.tree import export_graphviz
import xgboost
import lightgbm
from sklearn.metrics import roc_auc_score

In [391]:
df1=pd.read_csv ('/home/kamil.kural/FdaPrecision Challenge/sc2_Phase1_CN_FeatureMatrix.tsv', sep='\t')

In [392]:
df2=pd.read_csv ('/home/kamil.kural/FdaPrecision Challenge/sc2_Phase1_CN_Outcome.tsv', sep='\t')

In [393]:
df3=pd.read_csv ('/home/kamil.kural/FdaPrecision Challenge/sc2_Phase1_CN_Phenotype.tsv', sep='\t')

In [394]:
df = pd.merge(df2,
                    df1,
                    left_index=True,
                    right_index=True)
df = pd.merge(df,
                    df3,
                    left_index=True,
                    right_index=True)

In [395]:
df=df.drop(['PATIENTID','PATIENTID_x','PATIENTID_y'], axis=1)

In [396]:
dfnew= df[['11p15.4', 'RACE','9p24.1' ,'12p13.33', '9p21.3', 'SEX', '4q21.21' ,'20q11.21']]

In [397]:
dfnew=pd.get_dummies(dfnew)

In [398]:
dfnew

11p15.4             9p24.1           12p13.33  \
0    0.000000000000000  0.000000000000000  0.817851363922887   
1    0.606902015629110  0.000000000000000  1.129278112867650   
2    1.589997196313910  0.587040599393000  0.968627064949858   
3    0.850665569912331  0.000000000000000  0.000000000000000   
4    0.000000000000000  0.000000000000000  0.837517518127578   
5    1.515682679585340  0.586613619338478  0.000000000000000   
6    0.000000000000000  0.000000000000000  0.606609917978492   
7    0.000000000000000  0.000000000000000  0.615076498085350   
8    0.000000000000000  0.000000000000000  0.000000000000000   
9    0.000000000000000  2.795151585803320  0.000000000000000   
10   0.000000000000000  0.000000000000000  0.000000000000000   
11   0.000000000000000  0.000000000000000  0.000000000000000   
12   0.000000000000000  1.358711468282530  0.000000000000000   
13   0.000000000000000  2.792207842105120  0.000000000000000   
14   0.635725014707336  0.000000000000000  0.000000000000000   
15   0.000000000000000  0.000000000000000  0.000000000000000   
16   0.000000000000000  0.000000000000000  0.000000000000000   
17   0.000000000000000  0.000000000000000  0.000000000000000   
18   0.000000000000000  0.000000000000000  0.000000000000000   
19   0.000000000000000  2.664816200094120  0.000000000000000   
20   0.000000000000000  0.000000000000000  0.000000000000000   
21   0.000000000000000  2.155647907660000  0.000000000000000   
22   0.000000000000000  0.000000000000000  0.000000000000000   
23   0.000000000000000  0.000000000000000  0.000000000000000   
24   2.592420567359550  0.000000000000000  0.000000000000000   
25   0.000000000000000  2.661069303365760  0.818430818886554   
26   0.000000000000000  0.000000000000000  0.000000000000000   
27   0.664418778631990  0.000000000000000  0.919859948516733   
28   0.000000000000000  1.084008984320680  1.163005369095130   
29   0.000000000000000  0.000000000000000  0.709630793644187   
30   0.000000000000000  0.000000000000000  0.649594068374883   
31   1.017671142615200  0.000000000000000  0.000000000000000   
32   1.426328152792040  0.000000000000000  0.600237983774478   
33   0.000000000000000  0.000000000000000  0.000000000000000   
34   0.000000000000000  3.140213414600620  0.897969900602278   
35   0.000000000000000  1.596948058251870  0.751393106349518   
36   0.000000000000000  2.119657967319310  2.521895462151590   
37   0.616892122781165  1.499457965019410  0.694771598374071   
38   0.000000000000000  0.000000000000000  0.000000000000000   
39   0.000000000000000  0.797998868623667  2.897861360560240   
40   1.132959037085570  0.645502533832069  0.000000000000000   
41   2.027603229056070  1.405601013656990  1.176982619433560   
42   1.035420437297790  0.000000000000000  0.604884656512442   
43   0.000000000000000  2.312759329755430  0.000000000000000   
44   0.000000000000000  0.000000000000000  0.941877185432811   
45   0.000000000000000  0.596009765080190  1.982601429758690   
46   0.000000000000000  0.000000000000000  1.062629993400380   
47   0.000000000000000  0.593514172566138  1.502220105419650   
48   0.745409570917423  0.000000000000000  0.000000000000000   
49   0.614818758455386  1.765948066632540  0.000000000000000   
50   0.000000000000000  0.000000000000000  0.000000000000000   
51   0.651523168903370  0.000000000000000  1.216978512895160   
52   1.054845923497520  1.774038290328730  0.000000000000000   
53   0.000000000000000  1.900083467226590  1.262854651783580   
54   0.000000000000000  2.220901538738230  0.812173079334463   
55   0.000000000000000  0.000000000000000  0.614802205780507   
56   0.811845571468614  0.661717782807746  0.000000000000000   
57   0.000000000000000  0.000000000000000  0.000000000000000   
58   0.000000000000000  0.000000000000000  0.679496057391716   
59   0.000000000000000  0.000000000000000  1.256037836455970   
60   0.586113599363941  0.764684214252197  0.866379507922138   
61   0.000000000000000  0.684264926479311  1.65

In [399]:
all_features = [x for x in df.columns if x not in ['SURVIVAL_STATUS']]

In [400]:
X, y = dfnew, df['SURVIVAL_STATUS']
labelencoder_y_1 = LabelEncoder()
y = labelencoder_y_1.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0])

In [401]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
X = scaler.fit_transform(X)

In [402]:
X.shape

(174, 12)

In [403]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42,stratify=df['SURVIVAL_STATUS'])

In [226]:
from bayes_opt import BayesianOptimization
from sklearn.model_selection import cross_val_score

In [229]:
pbounds = {
    'learning_rate': (0.01, 1.0),
    'n_estimators': (100,200),
    'max_depth': (15,25),
    'subsample': (0.1, 1.0),  # Change for big datasets
    'colsample': (0.1, 1.0),  # Change for datasets with lots of features
    'gamma': (0, 5),
    'max_delta_step' : (0,5),
    'min_child_weight' : (0,5),
    'reg_alpha' : (0.1, 1),
    'reg_lambda' : (0.1,1),
    'scale_pos_weight' : (0.1, 1)}
 
def xgboost_hyper_param(learning_rate,
                        n_estimators,
                        max_depth,
                        subsample,
                        colsample,
                        gamma,
                        max_delta_step,
                        min_child_weight,
                        reg_alpha,
                        reg_lambda,
                        scale_pos_weight):
 
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
 
    clf = XGBClassifier(
        max_depth=max_depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        gamma=gamma,
        max_delta_step=max_delta_step,
        min_child_weight=min_child_weight,
        reg_lambda=reg_lambda,
        reg_alpha=reg_alpha,
        scale_pos_weight=scale_pos_weight)
    return np.mean(cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy',n_jobs=50))
 
 
optimizer = BayesianOptimization(
    f=xgboost_hyper_param,
    pbounds=pbounds,
    random_state=1)

In [230]:
optimizer.maximize(init_points=10, n_iter=20, acq='ei')

|   iter    |  target   | colsample |   gamma   | learni... | max_de... | max_depth | min_ch... | n_esti... | reg_alpha | reg_la... | scale_... | subsample |
-------------------------------------------------------------------------------------------------------------------------------------------------------------
|  1        |  0.7448   |  0.4753   |  3.602    |  0.01011  |  1.512    |  16.47    |  0.4617   |  118.6    |  0.411    |  0.4571   |  0.5849   |  0.4773   |
|  2        |  0.8012   |  0.7167   |  1.022    |  0.8793   |  0.1369   |  21.7     |  2.087    |  155.9    |  0.2263   |  0.2783   |  0.8207   |  0.9714   |
|  3        |  0.7678   |  0.3821   |  3.462    |  0.8776   |  4.473    |  15.85    |  0.1953   |  117.0    |  0.8903   |  0.1885   |  0.479    |  0.9621   |
|  4        |  0.6726   |  0.5798   |  3.459    |  0.3224   |  3.433    |  23.35    |  0.09144  |  175.0    |  0.99     |  0.7733   |  0.3524   |  0.8104   |
|  5        |  0.7268   |  0.1929   |  2.239    |  0

KeyboardInterrupt: 

In [25]:
optimizer.max

{'target': 0.7486772486772486,
 'params': {'colsample': 0.6970973480366033,
  'gamma': 3.1084786010456087,
  'learning_rate': 0.12359851322384142,
  'max_delta_step': 4.747446293535356,
  'max_depth': 19.499121334799405,
  'min_child_weight': 2.891948071935659,
  'n_estimators': 140.8136802761281,
  'reg_alpha': 0.31332428221872494,
  'reg_lambda': 0.9130415685060284,
  'scale_pos_weight': 0.6163115380050572,
  'subsample': 0.10258329432804308}}

In [231]:
model1=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.01, max_delta_step=5, max_depth=20,
              min_child_weight=5, missing=None, n_estimators=200, n_jobs=20,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0.1, reg_lambda=1, scale_pos_weight=0.4, seed=None,
              silent=None, subsample=1, class_weight='balanced')

In [232]:
eval_set = [(X_train, y_train), (X_test, y_test)]
eval_metric = ["auc","error"]
%time model1.fit(X_train,y_train,eval_metric =eval_metric, eval_set=eval_set)

[0]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[1]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[2]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[3]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[4]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[5]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[6]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[7]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0.257143
[8]	validation_0-auc:0.753922	validation_0-error:0.230216	validation_1-auc:0.615385	validation_1-error:0

XGBClassifier(base_score=0.5, booster='gbtree', class_weight='balanced',
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              gamma=0, learning_rate=0.01, max_delta_step=5, max_depth=20,
              min_child_weight=5, missing=None, n_estimators=200, n_jobs=20,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0.1, reg_lambda=1, scale_pos_weight=0.4, seed=None,
              silent=None, subsample=1, verbosity=1)

In [233]:
pred=model1.predict(X)

In [234]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.5116279069767442
Sensitivity :  0.8549618320610687
Accuracy :  0.7701149425287356
Confusion Matrix : 
 [ 22  21  19 112]


In [45]:
from sklearn.ensemble import RandomForestClassifier
pbounds = {
    
    'n_estimators': (100,500),
    'max_depth': (20, 500),  # Change for big datasets
    'min_samples_split': (0.1, 1),  # Change for datasets with lots of features
                                }
 
def rf_hyper_param(
                        n_estimators,
                        max_depth,
                        min_samples_split,
                        
                        ):
 
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
 
    clf = RandomForestClassifier(
        max_depth=max_depth,
        n_estimators=n_estimators,
        min_samples_split=min_samples_split,
        
        )
    return np.mean(cross_val_score(clf, X_train, y_train, cv=5, scoring='accuracy',n_jobs=50))
 
 
optimizer = BayesianOptimization(
    f=rf_hyper_param,
    pbounds=pbounds,
    random_state=1)

In [46]:
optimizer.maximize(init_points=10, n_iter=20, acq='ei')

|   iter    |  target   | max_depth | min_sa... | n_esti... |
-------------------------------------------------------------
|  1        |  0.7556   |  220.2    |  0.7483   |  100.0    |
|  2        |  0.741    |  165.1    |  0.2321   |  136.9    |
|  3        |  0.7556   |  109.4    |  0.411    |  258.7    |
|  4        |  0.7484   |  278.6    |  0.4773   |  374.1    |
|  5        |  0.7556   |  118.1    |  0.8903   |  111.0    |
|  6        |  0.7556   |  341.8    |  0.4756   |  323.5    |
|  7        |  0.7339   |  87.39    |  0.2783   |  420.3    |
|  8        |  0.7484   |  484.8    |  0.3821   |  376.9    |
|  9        |  0.7556   |  440.7    |  0.9051   |  134.0    |
|  10       |  0.7267   |  38.75    |  0.2528   |  451.3    |
|  11       |  0.7556   |  20.0     |  1.0      |  100.0    |
|  12       |  0.7556   |  20.6     |  0.8851   |  288.4    |
|  13       |  0.7556   |  387.7    |  0.8196   |  100.0    |
|  14       |  0.741    |  499.3    |  0.291    |  100.2    |
|  15   

In [235]:
randomforest = RandomForestClassifier(criterion='gini',n_estimators=400,max_depth=350,min_samples_split=0.1,min_impurity_decrease=0.0,min_weight_fraction_leaf=0.05,max_features='auto', min_samples_leaf=7,random_state=0,oob_score=True,class_weight='balanced_subsample')

In [236]:
randomforest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced_subsample',
                       criterion='gini', max_depth=350, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=7,
                       min_samples_split=0.1, min_weight_fraction_leaf=0.05,
                       n_estimators=400, n_jobs=None, oob_score=True,
                       random_state=0, verbose=0, warm_start=False)

In [237]:
pred=randomforest.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.8604651162790697
Sensitivity :  0.7938931297709924
Accuracy :  0.8103448275862069
Confusion Matrix : 
 [ 37   6  27 104]


In [238]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000] }
clf = GridSearchCV(LogisticRegression(penalty='l2'), param_grid)
GridSearchCV(cv=5,
             estimator=LogisticRegression(C=1.0, intercept_scaling=1, class_weight='balanced' ,
               dual=False, fit_intercept=True, penalty='l2', tol=0.0001,n_jobs=50,verbose= 1000),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]})

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight='balanced',
                                          dual=False, fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=50, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=1000,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [239]:
clf.fit(X_train,y_train)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [240]:
best_params = clf.best_params_
best_params

{'C': 1}

In [247]:
lr1=LogisticRegression(C=0.001, class_weight='balanced', dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=300, multi_class='ovr',
                                          n_jobs=20, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=1e-4, verbose=1,
                                          warm_start=False)

In [248]:
lr1.fit(X_train,y_train)

[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.6s finished


LogisticRegression(C=0.001, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=300, multi_class='ovr', n_jobs=20, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=1,
                   warm_start=False)

In [249]:
pred=lr1.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.8837209302325582
Sensitivity :  0.5725190839694656
Accuracy :  0.6494252873563219
Confusion Matrix : 
 [38  5 56 75]


In [250]:
def lgb_eval(num_leaves, feature_fraction, bagging_fraction, max_depth, lambda_l1, lambda_l2, min_split_gain, min_child_weight):
    params = {'application':'binary','num_iterations':300, 'learning_rate':0.05, 'early_stopping_round':100, 'metric':'auc'}
    params["num_leaves"] = round(num_leaves)
    params['feature_fraction'] = max(min(feature_fraction, 1), 0)
    params['bagging_fraction'] = max(min(bagging_fraction, 1), 0)
    params['max_depth'] = round(max_depth)
    params['lambda_l1'] = max(lambda_l1, 0)
    params['lambda_l2'] = max(lambda_l2, 0)
    params['min_split_gain'] = min_split_gain
    params['min_child_weight'] = min_child_weight
    cv_result = lgb.cv(params, train_data, nfold=n_folds, seed=random_seed, stratified=True, verbose_eval =200, metrics=['auc'])
    return max(cv_result['auc-mean'])

In [251]:
lgbBO = BayesianOptimization(lgb_eval, {'num_leaves': (24, 45),
                                        'feature_fraction': (0.1, 0.9),
                                        'bagging_fraction': (0.8, 1),
                                        'max_depth': (5, 8.99),
                                        'lambda_l1': (0, 5),
                                        'lambda_l2': (0, 3),
                                        'min_split_gain': (0.001, 0.1),
                                        'min_child_weight': (5, 50)}, random_state=0)

In [253]:
def bayes_parameter_opt_lgb(X_train, y_train, init_round=15, opt_round=25, n_folds=5, random_seed=0, n_estimators=10000, learning_rate=0.05, output_process=False):
    # prepare data
    train_data = lgb.Dataset(data=X_train, label=y_train)
    # parameters
    def lgb_eval(num_leaves, feature_fraction, bagging_fraction, max_depth, lambda_l1, lambda_l2, min_split_gain, min_child_weight,n_jobs=20):
        params = {'application':'binary','num_iterations': n_estimators, 'learning_rate':learning_rate, 'early_stopping_round':100, 'metric':'auc'}
        params["num_leaves"] = int(round(num_leaves))
        params['feature_fraction'] = max(min(feature_fraction, 1), 0)
        params['bagging_fraction'] = max(min(bagging_fraction, 1), 0)
        params['max_depth'] = int(round(max_depth))
        params['lambda_l1'] = max(lambda_l1, 0)
        params['lambda_l2'] = max(lambda_l2, 0)
        params['min_split_gain'] = min_split_gain
        params['min_child_weight'] = min_child_weight
        cv_result = lgb.cv(params, train_data, nfold=n_folds, seed=random_seed, stratified=True, verbose_eval =200, metrics=['auc'])
        return max(cv_result['auc-mean'])
    # range 
    lgbBO = BayesianOptimization(lgb_eval, {'num_leaves': (24, 45),
                                            'feature_fraction': (0.1, 0.9),
                                            'bagging_fraction': (0.8, 1),
                                            'max_depth': (5, 25),
                                            'lambda_l1': (0, 5),
                                            'lambda_l2': (0, 3),
                                            'min_split_gain': (0.001, 0.1),
                                            'min_child_weight': (1, 10)}, random_state=0)
    # optimize
    lgbBO.maximize(init_points=init_round, n_iter=opt_round)
    
    # output optimization process
    if output_process==True: lgbBO.points_to_csv("bayes_opt_result.csv")
    
    # return best parameters
    

opt_params = bayes_parameter_opt_lgb(X, y, init_round=10, opt_round=20, n_folds=5, random_seed=0, n_estimators=100, learning_rate=0.1)

|   iter    |  target   | baggin... | featur... | lambda_l1 | lambda_l2 | max_depth | min_ch... | min_sp... | num_le... |
-------------------------------------------------------------------------------------------------------------------------
|  1        |  0.6539   |  0.9098   |  0.6722   |  3.014    |  1.635    |  13.47    |  6.813    |  0.04432  |  42.73    |
|  2        |  0.651    |  0.9927   |  0.4068   |  3.959    |  1.587    |  16.36    |  9.33     |  0.008033 |  25.83    |
|  3        |  0.658    |  0.804    |  0.7661   |  3.891    |  2.61     |  24.57    |  8.192    |  0.04669  |  40.39    |
|  4        |  0.7611   |  0.8237   |  0.6119   |  0.7168   |  2.834    |  15.44    |  4.732    |  0.02719  |  40.26    |
|  5        |  0.7619   |  0.8912   |  0.5547   |  0.09395  |  1.853    |  17.24    |  6.552    |  0.09443  |  38.32    |
|  6        |  0.6635   |  0.8719   |  0.4496   |  3.488    |  0.1807   |  18.34    |  7.036    |  0.02183  |  26.71    |
|  7        |  0.7716   

In [299]:
from lightgbm import LGBMClassifier
model2=LGBMClassifier(num_leaves= 45, feature_fraction= 0.1, learning_rate= 0.5, bagging_fraction= 1, max_depth= 25,scale_pos_weight=0.37, min_child_weight= 0.0001, n_estimators= 200, lambda_l1= 0, lambda_l2= 0, min_split_gain=0.0001, n_jobs= 20, verbose=1)

In [300]:
model2.fit(X_train,y_train,eval_metric =eval_metric, eval_set=eval_set, verbose=100)

[100]	valid_0's auc: 0.988796	valid_0's binary_logloss: 0.141276	valid_1's auc: 0.764957	valid_1's binary_logloss: 0.828981
[200]	valid_0's auc: 0.996639	valid_0's binary_logloss: 0.0866109	valid_1's auc: 0.747863	valid_1's binary_logloss: 1.23379


LGBMClassifier(bagging_fraction=1, boosting_type='gbdt', class_weight=None,
               colsample_bytree=1.0, feature_fraction=0.1,
               importance_type='split', lambda_l1=0, lambda_l2=0,
               learning_rate=0.5, max_depth=25, min_child_samples=20,
               min_child_weight=0.0001, min_split_gain=0.0001, n_estimators=200,
               n_jobs=20, num_leaves=45, objective=None, random_state=None,
               reg_alpha=0.0, reg_lambda=0.0, scale_pos_weight=0.37,
               silent=True, subsample=1.0, subsample_for_bin=200000,
               subsample_freq=0, verbose=1)

In [301]:
pred=model2.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.9302325581395349
Sensitivity :  0.9236641221374046
Accuracy :  0.9252873563218391
Confusion Matrix : 
 [ 40   3  10 121]


In [302]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       0.80      0.93      0.86        43
           1       0.98      0.92      0.95       131

    accuracy                           0.93       174
   macro avg       0.89      0.93      0.90       174
weighted avg       0.93      0.93      0.93       174



In [303]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
#List Hyperparameters that we want to tune.
n_neighbors = list(range(1,50))
p=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
#Convert to dictionary
hyperparameters = dict( n_neighbors=n_neighbors, p=p)
#Create new KNN object
knn_2 = KNeighborsClassifier()
#Use GridSearch
clf = GridSearchCV(knn_2, hyperparameters, cv=10, n_jobs=50,verbose=1,scoring='roc_auc')
#Fit the model
best_model = clf.fit(X,y)
#Print The value of best Hyperparameters
print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
print('Best p:', best_model.best_estimator_.get_params()['p'])
print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])

Fitting 10 folds for each of 735 candidates, totalling 7350 fits


[Parallel(n_jobs=50)]: Using backend LokyBackend with 50 concurrent workers.
[Parallel(n_jobs=50)]: Done 100 tasks      | elapsed:    1.4s
[Parallel(n_jobs=50)]: Done 600 tasks      | elapsed:    1.7s
[Parallel(n_jobs=50)]: Done 4800 tasks      | elapsed:    3.3s


Best leaf_size: 30
Best p: 1
Best n_neighbors: 12


[Parallel(n_jobs=50)]: Done 7350 out of 7350 | elapsed:    3.7s finished


In [306]:
knn = KNeighborsClassifier(leaf_size=30, p=1, n_neighbors= 12,weights='distance')

In [307]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=12, p=1,
                     weights='distance')

In [308]:
pred=knn.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.9069767441860465
Sensitivity :  0.9541984732824428
Accuracy :  0.9425287356321839
Confusion Matrix : 
 [ 39   4   6 125]


In [309]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.9305876087342447

In [310]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       0.87      0.91      0.89        43
           1       0.97      0.95      0.96       131

    accuracy                           0.94       174
   macro avg       0.92      0.93      0.92       174
weighted avg       0.94      0.94      0.94       174



In [313]:
from sklearn.ensemble import VotingClassifier

voting_classifier = VotingClassifier(estimators=[
     
    
    ('lgb', model2), 
    ('knn', knn)],voting='hard')
voting_classifier.fit(X_train,y_train)

VotingClassifier(estimators=[('lgb',
                              LGBMClassifier(bagging_fraction=1,
                                             boosting_type='gbdt',
                                             class_weight=None,
                                             colsample_bytree=1.0,
                                             feature_fraction=0.1,
                                             importance_type='split',
                                             lambda_l1=0, lambda_l2=0,
                                             learning_rate=0.5, max_depth=25,
                                             min_child_samples=20,
                                             min_child_weight=0.0001,
                                             min_split_gain=0.0001,
                                             n_estimators=200, n_jobs=20,
                                             num_leaves=45, objective=None,
                                             random_state=N

In [404]:
pred=voting_classifier.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.9534883720930233
Sensitivity :  0.9236641221374046
Accuracy :  0.9310344827586207
Confusion Matrix : 
 [ 41   2  10 121]


In [405]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.938576247115214

In [370]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       0.80      0.95      0.87        43
           1       0.98      0.92      0.95       131

    accuracy                           0.93       174
   macro avg       0.89      0.94      0.91       174
weighted avg       0.94      0.93      0.93       174



In [371]:
from mlxtend.classifier import StackingCVClassifier
lr = LogisticRegression(C=0.01)
sclf = StackingCVClassifier(classifiers = [ model2, knn],
                            shuffle = False,
                            use_probas = True,
                            cv = 5,
                            meta_classifier = lr1)

In [372]:
sclf.fit(X_train, y_train)

[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.7s finished


StackingCVClassifier(classifiers=[LGBMClassifier(bagging_fraction=1,
                                                 boosting_type='gbdt',
                                                 class_weight=None,
                                                 colsample_bytree=1.0,
                                                 feature_fraction=0.1,
                                                 importance_type='split',
                                                 lambda_l1=0, lambda_l2=0,
                                                 learning_rate=0.5,
                                                 max_depth=25,
                                                 min_child_samples=20,
                                                 min_child_weight=0.0001,
                                                 min_split_gain=0.0001,
                                                 n_estimators=200, n_jobs=20,
                                                 num_leaves=45, objective=N

In [373]:
pred=sclf.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.9302325581395349
Sensitivity :  0.9236641221374046
Accuracy :  0.9252873563218391
Confusion Matrix : 
 [ 40   3  10 121]


In [148]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.8618853186579088