In [1]:
!cd /home/kamil.kural/FdaPrecision Challenge

/usr/bin/sh: line 0: cd: /home/kamil.kural/FdaPrecision: No such file or directory


In [2]:
import numpy as np
import pandas as pd
import os
import copy
import matplotlib.pyplot as plt
%matplotlib inline
from tqdm import tqdm_notebook
from sklearn.preprocessing import StandardScaler
from sklearn.svm import NuSVR, SVR
from sklearn.metrics import mean_absolute_error
pd.options.display.precision = 15
from collections import defaultdict
import lightgbm as lgb
import xgboost as xgb
import catboost as cat
import time
import datetime
from catboost import CatBoostRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold, KFold, RepeatedKFold, GroupKFold, GridSearchCV, train_test_split, TimeSeriesSplit, RepeatedStratifiedKFold
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import linear_model
import gc
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import eli5
import shap
from IPython.display import HTML
import json
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline
from typing import List

import os
import time
import datetime
import json
import gc
from numba import jit

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm_notebook

import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor, CatBoostClassifier
from sklearn import metrics
from typing import Any
from itertools import product
pd.set_option('max_rows', 500)
import re
from tqdm import tqdm
from joblib import Parallel, delayed

Using TensorFlow backend.


In [3]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier,VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from IPython.display import display
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.tree import export_graphviz
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import GridSearchCV
import torch 
import fastai
import bayes_opt
import xgboost
import lightgbm

In [4]:
df1=pd.read_csv ('/home/kamil.kural/FdaPrecision Challenge/sc1_Phase1_GE_FeatureMatrix.tsv', sep='\t')

In [5]:
df2=pd.read_csv ('/home/kamil.kural/FdaPrecision Challenge/sc1_Phase1_GE_Outcome.tsv', sep='\t')

In [6]:
df3=pd.read_csv ('/home/kamil.kural/FdaPrecision Challenge/sc1_Phase1_GE_Phenotype.tsv', sep='\t')

In [7]:
df = pd.merge(df2,
                    df1,
                    left_index=True,
                    right_index=True)
df = pd.merge(df,
                    df3,
                    left_index=True,
                    right_index=True)

In [8]:
df=df.drop(['PATIENTID','PATIENTID_x','PATIENTID_y'], axis=1)

In [9]:
dfnew= df[['PCMTD1', 'ARAP3','DYNLL2' ,'HAUS4', 'C4orf19', 'SMARCC2', 'CASTOR1' ,'PDCD4','SYCP2', 'ACBD4','SMU1' ,'SETD1A']]

In [10]:
categorical_list = []
numerical_list = []
for i in dfnew.columns.tolist():
    if dfnew[i].dtype=='object':
        categorical_list.append(i)
    else:
        numerical_list.append(i)
print('Number of categorical features:', str(len(categorical_list)))
print('Number of numerical features:', str(len(numerical_list)))

Number of categorical features: 0
Number of numerical features: 12


In [11]:
categorical_list

[]

In [12]:
X = dfnew
y = df.SURVIVAL_STATUS
feature_name = X.columns.tolist()

In [13]:
all_features = [x for x in dfnew.columns if x not in ['SURVIVAL_STATUS']]

In [14]:
X, y = df[all_features], df['SURVIVAL_STATUS']
labelencoder_y_1 = LabelEncoder()
y = labelencoder_y_1.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [15]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
X=pd.get_dummies(X)
X = scaler.fit_transform(X)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42,stratify=df['SURVIVAL_STATUS'])

In [17]:
from bayes_opt import BayesianOptimization
from sklearn.model_selection import cross_val_score

In [174]:
pbounds = {
    'learning_rate': (0.01, 1.0),
    'n_estimators': (100,200),
    'max_depth': (15,25),
    'subsample': (0.5, 1.0),  # Change for big datasets
    'colsample': (0.5, 1.0),  # Change for datasets with lots of features
    'gamma': (0, 5),
    'max_delta_step' : (0,5),
    'min_child_weight' : (0,5),
    'reg_alpha' : (0.1, 1),
    'reg_lambda' : (0.1,1),
    'scale_pos_weight' : (0.1, 1)}
 
def xgboost_hyper_param(learning_rate,
                        n_estimators,
                        max_depth,
                        subsample,
                        colsample,
                        gamma,
                        max_delta_step,
                        min_child_weight,
                        reg_alpha,
                        reg_lambda,
                        scale_pos_weight):
 
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
 
    clf = XGBClassifier(
        max_depth=max_depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        gamma=gamma,
        max_delta_step=max_delta_step,
        min_child_weight=min_child_weight,
        reg_lambda=reg_lambda,
        reg_alpha=reg_alpha,
        scale_pos_weight=scale_pos_weight)
    return np.mean(cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy',n_jobs=50))
 
 
optimizer = BayesianOptimization(
    f=xgboost_hyper_param,
    pbounds=pbounds,
    random_state=1)

In [ ]:
optimizer.maximize(init_points=10, n_iter=20, acq='ei')

|   iter    |  target   | colsample |   gamma   | learni... | max_de... | max_depth | min_ch... | n_esti... | reg_alpha | reg_la... | scale_... | subsample |
-------------------------------------------------------------------------------------------------------------------------------------------------------------
|  1        |  0.8705   |  0.7085   |  3.602    |  0.01011  |  1.512    |  16.47    |  0.4617   |  118.6    |  0.411    |  0.4571   |  0.5849   |  0.7096   |
|  2        |  0.8905   |  0.8426   |  1.022    |  0.8793   |  0.1369   |  21.7     |  2.087    |  155.9    |  0.2263   |  0.2783   |  0.8207   |  0.9841   |
|  3        |  0.8604   |  0.6567   |  3.462    |  0.8776   |  4.473    |  15.85    |  0.1953   |  117.0    |  0.8903   |  0.1885   |  0.479    |  0.9789   |
|  4        |  0.8838   |  0.7666   |  3.459    |  0.3224   |  3.433    |  23.35    |  0.09144  |  175.0    |  0.99     |  0.7733   |  0.3524   |  0.8946   |
|  5        |  0.8571   |  0.5516   |  2.239    |  0

In [54]:
optimizer.max

{'target': 0.8905376344086022,
 'params': {'colsample': 0.8426097501983798,
  'gamma': 1.0222612486575873,
  'learning_rate': 0.879336262027036,
  'max_delta_step': 0.13693796598963082,
  'max_depth': 21.704675101784023,
  'min_child_weight': 2.086524011835635,
  'n_estimators': 155.86898284457516,
  'reg_alpha': 0.2263482447357104,
  'reg_lambda': 0.2782913401763909,
  'scale_pos_weight': 0.820670111807983,
  'subsample': 0.9841307878596988}}

In [20]:
model=XGBClassifier(colsample= 1, gamma= 0, learning_rate= 0.1, max_delta_step= 5, max_depth= 25, min_child_weight= 0.0001, n_estimators= 100, reg_alpha= 0.1, reg_lambda= 1, scale_pos_weight=0.5, subsample= 0.5)

In [21]:
eval_set = [(X_train, y_train), (X_test, y_test)]
eval_metric = ["auc","error"]
%time model.fit(X_train,y_train,eval_metric =eval_metric, eval_set=eval_set, verbose=True)

[0]	validation_0-auc:0.904362	validation_0-error:0.066445	validation_1-auc:0.708333	validation_1-error:0.184211
[1]	validation_0-auc:0.964681	validation_0-error:0.083056	validation_1-auc:0.689394	validation_1-error:0.171053
[2]	validation_0-auc:0.977908	validation_0-error:0.039867	validation_1-auc:0.705303	validation_1-error:0.131579
[3]	validation_0-auc:0.985882	validation_0-error:0.023256	validation_1-auc:0.768182	validation_1-error:0.171053
[4]	validation_0-auc:0.986116	validation_0-error:0.043189	validation_1-auc:0.777273	validation_1-error:0.144737
[5]	validation_0-auc:0.985084	validation_0-error:0.043189	validation_1-auc:0.769697	validation_1-error:0.157895
[6]	validation_0-auc:0.98743	validation_0-error:0.056478	validation_1-auc:0.775	validation_1-error:0.144737
[7]	validation_0-auc:0.986679	validation_0-error:0.056478	validation_1-auc:0.763636	validation_1-error:0.157895
[8]	validation_0-auc:0.989306	validation_0-error:0.053156	validation_1-auc:0.8	validation_1-error:0.144737
[

XGBClassifier(base_score=0.5, booster='gbtree', colsample=1,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              gamma=0, learning_rate=0.1, max_delta_step=5, max_depth=25,
              min_child_weight=0.0001, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0.1, reg_lambda=1, scale_pos_weight=0.5, seed=None,
              silent=None, subsample=0.5, verbosity=1)

In [64]:
pred=model.predict(X)

In [65]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.8431372549019608
Sensitivity :  0.9969325153374233
Accuracy :  0.9761273209549072
Confusion Matrix : 
 [ 43   8   1 325]


In [66]:
from sklearn.metrics import roc_auc_score
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.9200348851196921

In [80]:
from sklearn.ensemble import RandomForestClassifier
pbounds = {
    
    'n_estimators': (100,500),
    'max_depth': (20, 500),  # Change for big datasets
    'min_samples_split': (0.1, 1),  # Change for datasets with lots of features
                                }
 
def rf_hyper_param(
                        n_estimators,
                        max_depth,
                        min_samples_split,
                        
                        ):
 
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
 
    clf = RandomForestClassifier(
        max_depth=max_depth,
        n_estimators=n_estimators,
        min_samples_split=min_samples_split,
        
        )
    return np.mean(cross_val_score(clf, X_train, y_train, cv=10, scoring='roc_auc',n_jobs=50))
 
 
optimizer = BayesianOptimization(
    f=rf_hyper_param,
    pbounds=pbounds,
    random_state=1)

In [81]:
optimizer.maximize(init_points=10, n_iter=20, acq='ei')

|   iter    |  target   | max_depth | min_sa... | n_esti... |
-------------------------------------------------------------
|  1        |  0.5      |  220.2    |  0.7483   |  100.0    |
|  2        |  0.8551   |  165.1    |  0.2321   |  136.9    |
|  3        |  0.8399   |  109.4    |  0.411    |  258.7    |
|  4        |  0.8472   |  278.6    |  0.4773   |  374.1    |
|  5        |  0.5      |  118.1    |  0.8903   |  111.0    |
|  6        |  0.8519   |  341.8    |  0.4756   |  323.5    |
|  7        |  0.8468   |  87.39    |  0.2783   |  420.3    |
|  8        |  0.846    |  484.8    |  0.3821   |  376.9    |
|  9        |  0.5      |  440.7    |  0.9051   |  134.0    |
|  10       |  0.852    |  38.75    |  0.2528   |  451.3    |
|  11       |  0.8554   |  198.9    |  0.1      |  217.3    |
|  12       |  0.849    |  373.4    |  0.1      |  500.0    |
|  13       |  0.849    |  186.5    |  0.1      |  500.0    |
|  14       |  0.5      |  500.0    |  1.0      |  500.0    |
|  15   

In [24]:
randomforest = RandomForestClassifier(criterion='gini',n_estimators=217,max_depth=200,min_samples_split=0.1,min_impurity_decrease=0.0,min_weight_fraction_leaf=0.0,max_features='auto', min_samples_leaf=3,random_state=0,oob_score=True,class_weight='balanced_subsample')

In [25]:
randomforest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced_subsample',
                       criterion='gini', max_depth=200, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=3,
                       min_samples_split=0.1, min_weight_fraction_leaf=0.0,
                       n_estimators=217, n_jobs=None, oob_score=True,
                       random_state=0, verbose=0, warm_start=False)

In [67]:
pred=randomforest.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.8431372549019608
Sensitivity :  0.9171779141104295
Accuracy :  0.9071618037135278
Confusion Matrix : 
 [ 43   8  27 299]


In [68]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.8801575845061951

In [27]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000] }
clf = GridSearchCV(LogisticRegression(penalty='l2'), param_grid)
GridSearchCV(cv=5,
             estimator=LogisticRegression(C=1.0, intercept_scaling=1, class_weight='balanced' ,
               dual=False, fit_intercept=True, penalty='l2', tol=0.0001,n_jobs=50,verbose= 1000),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]})

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight='balanced',
                                          dual=False, fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=50, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=1000,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [28]:
clf.fit(X_train,y_train)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [29]:
best_params = clf.best_params_

In [30]:
best_params

{'C': 0.1}

In [37]:
lr1=LogisticRegression(C=0.001,class_weight='balanced', dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=300, multi_class='ovr',
                                          n_jobs=20, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=1e-7, verbose=1,
                                          warm_start=False)

In [38]:
lr1.fit(X_train,y_train)

[Parallel(n_jobs=20)]: Using backend LokyBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 out of   1 | elapsed:    0.5s finished


LogisticRegression(C=0.001, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=300, multi_class='ovr', n_jobs=20, penalty='l2',
                   random_state=None, solver='lbfgs', tol=1e-07, verbose=1,
                   warm_start=False)

In [69]:
pred=lr1.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.6470588235294118
Sensitivity :  0.7944785276073619
Accuracy :  0.7745358090185677
Confusion Matrix : 
 [ 33  18  67 259]


In [70]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.7207686755683869

In [40]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       0.33      0.65      0.44        51
           1       0.94      0.79      0.86       326

    accuracy                           0.77       377
   macro avg       0.63      0.72      0.65       377
weighted avg       0.85      0.77      0.80       377



In [41]:
def lgb_eval(num_leaves, feature_fraction, bagging_fraction, max_depth, lambda_l1, lambda_l2, min_split_gain, min_child_weight):
    params = {'application':'binary','num_iterations':300, 'learning_rate':0.05, 'early_stopping_round':100, 'metric':'auc'}
    params["num_leaves"] = round(num_leaves)
    params['feature_fraction'] = max(min(feature_fraction, 1), 0)
    params['bagging_fraction'] = max(min(bagging_fraction, 1), 0)
    params['max_depth'] = round(max_depth)
    params['lambda_l1'] = max(lambda_l1, 0)
    params['lambda_l2'] = max(lambda_l2, 0)
    params['min_split_gain'] = min_split_gain
    params['min_child_weight'] = min_child_weight
    cv_result = lgb.cv(params, train_data, nfold=n_folds, seed=random_seed, stratified=True, verbose_eval =200, metrics=['auc'])
    return max(cv_result['auc-mean'])

In [42]:
lgbBO = BayesianOptimization(lgb_eval, {'num_leaves': (24, 45),
                                        'feature_fraction': (0.1, 0.9),
                                        'bagging_fraction': (0.8, 1),
                                        'max_depth': (5, 8.99),
                                        'lambda_l1': (0, 5),
                                        'lambda_l2': (0, 3),
                                        'min_split_gain': (0.001, 0.1),
                                        'min_child_weight': (5, 50)}, random_state=0)

In [43]:
def bayes_parameter_opt_lgb(X_train, y_train, init_round=15, opt_round=25, n_folds=5, random_seed=0, n_estimators=10000, learning_rate=0.05, output_process=False):
    # prepare data
    train_data = lgb.Dataset(data=X_train, label=y_train)
    # parameters
    def lgb_eval(num_leaves, feature_fraction, bagging_fraction, max_depth, lambda_l1, lambda_l2, min_split_gain, min_child_weight,n_jobs=20):
        params = {'application':'binary','num_iterations': n_estimators, 'learning_rate':learning_rate, 'early_stopping_round':100, 'metric':'auc'}
        params["num_leaves"] = int(round(num_leaves))
        params['feature_fraction'] = max(min(feature_fraction, 1), 0)
        params['bagging_fraction'] = max(min(bagging_fraction, 1), 0)
        params['max_depth'] = int(round(max_depth))
        params['lambda_l1'] = max(lambda_l1, 0)
        params['lambda_l2'] = max(lambda_l2, 0)
        params['min_split_gain'] = min_split_gain
        params['min_child_weight'] = min_child_weight
        cv_result = lgb.cv(params, train_data, nfold=n_folds, seed=random_seed, stratified=True, verbose_eval =200, metrics=['auc'])
        return max(cv_result['auc-mean'])
    # range 
    lgbBO = BayesianOptimization(lgb_eval, {'num_leaves': (24, 45),
                                            'feature_fraction': (0.1, 0.9),
                                            'bagging_fraction': (0.8, 1),
                                            'max_depth': (5, 25),
                                            'lambda_l1': (0, 5),
                                            'lambda_l2': (0, 3),
                                            'min_split_gain': (0.001, 0.1),
                                            'min_child_weight': (1, 10)}, random_state=0)
    # optimize
    lgbBO.maximize(init_points=init_round, n_iter=opt_round)
    
    # output optimization process
    if output_process==True: lgbBO.points_to_csv("bayes_opt_result.csv")
    
    # return best parameters
    

opt_params = bayes_parameter_opt_lgb(X_train, y_train, init_round=10, opt_round=20, n_folds=5, random_seed=0, n_estimators=100, learning_rate=0.01)

|   iter    |  target   | baggin... | featur... | lambda_l1 | lambda_l2 | max_depth | min_ch... | min_sp... | num_le... |
-------------------------------------------------------------------------------------------------------------------------
|  1        |  0.7579   |  0.9098   |  0.6722   |  3.014    |  1.635    |  13.47    |  6.813    |  0.04432  |  42.73    |
|  2        |  0.748    |  0.9927   |  0.4068   |  3.959    |  1.587    |  16.36    |  9.33     |  0.008033 |  25.83    |
|  3        |  0.7504   |  0.804    |  0.7661   |  3.891    |  2.61     |  24.57    |  8.192    |  0.04669  |  40.39    |
|  4        |  0.7302   |  0.8237   |  0.6119   |  0.7168   |  2.834    |  15.44    |  4.732    |  0.02719  |  40.26    |
|  5        |  0.7407   |  0.8912   |  0.5547   |  0.09395  |  1.853    |  17.24    |  6.552    |  0.09443  |  38.32    |
|  6        |  0.7808   |  0.8719   |  0.4496   |  3.488    |  0.1807   |  18.34    |  7.036    |  0.02183  |  26.71    |
|  7        |  0.8009   

KeyboardInterrupt: 

In [48]:
from lightgbm import LGBMClassifier
model2=LGBMClassifier(num_leaves= 25, feature_fraction= 0.8874  , learning_rate= 0.01, bagging_fraction= 0.9114  , max_depth= 25,scale_pos_weight=0.5, min_child_weight= 0.5, n_estimators= 156, lambda_l1= 0.01122 , lambda_l2= 0.08378 , min_split_gain=0.05922 , n_jobs= 20, verbose=1)

In [49]:
model2.fit(X_train,y_train,eval_metric =eval_metric, eval_set=eval_set, verbose=True)

[1]	valid_0's auc: 0.870779	valid_0's binary_logloss: 0.394793	valid_1's auc: 0.717424	valid_1's binary_logloss: 0.387809
[2]	valid_0's auc: 0.907317	valid_0's binary_logloss: 0.391399	valid_1's auc: 0.783333	valid_1's binary_logloss: 0.385548
[3]	valid_0's auc: 0.905629	valid_0's binary_logloss: 0.388413	valid_1's auc: 0.760606	valid_1's binary_logloss: 0.384051
[4]	valid_0's auc: 0.907317	valid_0's binary_logloss: 0.385265	valid_1's auc: 0.790909	valid_1's binary_logloss: 0.381954
[5]	valid_0's auc: 0.91182	valid_0's binary_logloss: 0.382242	valid_1's auc: 0.8	valid_1's binary_logloss: 0.379946
[6]	valid_0's auc: 0.914071	valid_0's binary_logloss: 0.379373	valid_1's auc: 0.814394	valid_1's binary_logloss: 0.378458
[7]	valid_0's auc: 0.910038	valid_0's binary_logloss: 0.37657	valid_1's auc: 0.800758	valid_1's binary_logloss: 0.376596
[8]	valid_0's auc: 0.907598	valid_0's binary_logloss: 0.373872	valid_1's auc: 0.802273	valid_1's binary_logloss: 0.374808
[9]	valid_0's auc: 0.921341	val

LGBMClassifier(bagging_fraction=0.9114, boosting_type='gbdt', class_weight=None,
               colsample_bytree=1.0, feature_fraction=0.8874,
               importance_type='split', lambda_l1=0.01122, lambda_l2=0.08378,
               learning_rate=0.01, max_depth=25, min_child_samples=20,
               min_child_weight=0.5, min_split_gain=0.05922, n_estimators=156,
               n_jobs=20, num_leaves=25, objective=None, random_state=None,
               reg_alpha=0.0, reg_lambda=0.0, scale_pos_weight=0.5, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0,
               verbose=1)

In [71]:
pred=model2.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.5098039215686274
Sensitivity :  1.0
Accuracy :  0.9336870026525199
Confusion Matrix : 
 [ 26  25   0 326]


In [72]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.7549019607843137

In [73]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       1.00      0.51      0.68        51
           1       0.93      1.00      0.96       326

    accuracy                           0.93       377
   macro avg       0.96      0.75      0.82       377
weighted avg       0.94      0.93      0.92       377



In [88]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
#List Hyperparameters that we want to tune.
n_neighbors = list(range(1,30))
p=[1,2,3,4,5,6,7,8,9,10]
#Convert to dictionary
hyperparameters = dict( n_neighbors=n_neighbors, p=p)
#Create new KNN object
knn_2 = KNeighborsClassifier()
#Use GridSearch
clf = GridSearchCV(knn_2, hyperparameters, cv=10, n_jobs=50,verbose=1)
#Fit the model
best_model = clf.fit(X,y)
#Print The value of best Hyperparameters
print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
print('Best p:', best_model.best_estimator_.get_params()['p'])
print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])

Fitting 10 folds for each of 290 candidates, totalling 2900 fits


[Parallel(n_jobs=50)]: Using backend LokyBackend with 50 concurrent workers.
[Parallel(n_jobs=50)]: Done 100 tasks      | elapsed:    1.1s
[Parallel(n_jobs=50)]: Done 600 tasks      | elapsed:    1.6s
[Parallel(n_jobs=50)]: Done 2355 tasks      | elapsed:    2.4s


Best leaf_size: 30
Best p: 1
Best n_neighbors: 14


[Parallel(n_jobs=50)]: Done 2900 out of 2900 | elapsed:    2.8s finished


In [89]:
knn = KNeighborsClassifier(leaf_size=30, p=1, n_neighbors= 14,weights='distance')

In [90]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=14, p=1,
                     weights='distance')

In [91]:
pred=knn.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.8235294117647058
Sensitivity :  0.9969325153374233
Accuracy :  0.9734748010610079
Confusion Matrix : 
 [ 42   9   1 325]


In [92]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.9102309635510646

In [56]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       0.98      0.82      0.89        51
           1       0.97      1.00      0.98       326

    accuracy                           0.97       377
   macro avg       0.97      0.91      0.94       377
weighted avg       0.97      0.97      0.97       377



In [151]:
from sklearn.linear_model import RidgeClassifier
develop = True
seed = 0

    
def target(**params):
    fit_intercept = int(params['fit_intercept'])
    fit_intercept_dict = {0:False, 1:True}

    model = RidgeClassifier(alpha = params['alpha'],
                    fit_intercept = fit_intercept_dict[fit_intercept],
                    copy_X = True,class_weight='balanced' )
    
    scores = cross_val_score(model, X_train, y_train, scoring='roc_auc', cv=5)
    return scores.mean()
    
params = {'alpha':(1, 50),
          'fit_intercept':(0,1.99)}
if develop:
    bo = BayesianOptimization(target, params, random_state=seed)
    bo.maximize(init_points=5, n_iter=10, acq='ucb')
    

|   iter    |  target   |   alpha   | fit_in... |
-------------------------------------------------
|  1        |  0.794    |  27.89    |  1.423    |
|  2        |  0.7935   |  30.54    |  1.084    |
|  3        |  0.7929   |  21.76    |  1.285    |
|  4        |  0.7934   |  22.44    |  1.775    |
|  5        |  0.7933   |  48.22    |  0.763    |
|  6        |  0.7849   |  1.004    |  0.003511 |
|  7        |  0.7973   |  49.94    |  1.983    |
|  8        |  0.7973   |  49.98    |  1.976    |
|  9        |  0.7973   |  49.64    |  1.989    |
|  10       |  0.7973   |  49.98    |  1.989    |
|  11       |  0.7973   |  49.97    |  1.985    |
|  12       |  0.7973   |  49.99    |  1.981    |
|  13       |  0.7973   |  49.98    |  1.981    |
|  14       |  0.7973   |  49.89    |  1.983    |
|  15       |  0.7973   |  49.67    |  1.989    |


In [159]:
ridgemodel = RidgeClassifier(alpha = 49.94    ,
                  fit_intercept = 1.983    , class_weight='balanced',
                  copy_X = True)

ridgemodel.fit(X_train, y_train)
pred = ridgemodel.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.6470588235294118
Sensitivity :  0.7944785276073619
Accuracy :  0.7745358090185677
Confusion Matrix : 
 [ 33  18  67 259]


In [93]:
from sklearn.ensemble import VotingClassifier

voting_classifier = VotingClassifier(estimators=[
    ('xgb',model), 
    ('knn', knn)],voting='hard')
voting_classifier.fit(X_train,y_train)

VotingClassifier(estimators=[('xgb',
                              XGBClassifier(base_score=0.5, booster='gbtree',
                                            colsample=1, colsample_bylevel=1,
                                            colsample_bynode=1,
                                            colsample_bytree=1, gamma=0,
                                            learning_rate=0.1, max_delta_step=5,
                                            max_depth=25,
                                            min_child_weight=0.0001,
                                            missing=None, n_estimators=100,
                                            n_jobs=1, nthread=None,
                                            objective='binary:logistic',
                                            random_state=0, reg_alpha=0.1,
                                            reg_lambda=1, scale_pos_weight=0.5,
                                            seed=None, silent=None,
                      

In [94]:
pred=voting_classifier.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.8431372549019608
Sensitivity :  0.9938650306748467
Accuracy :  0.9734748010610079
Confusion Matrix : 
 [ 43   8   2 324]


In [86]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)

0.9185011427884038

In [82]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       0.96      0.84      0.90        51
           1       0.98      0.99      0.98       326

    accuracy                           0.97       377
   macro avg       0.97      0.92      0.94       377
weighted avg       0.97      0.97      0.97       377



In [95]:
from mlxtend.classifier import StackingCVClassifier
lr = LogisticRegression()
sclf = StackingCVClassifier(classifiers = [model, knn],
                            shuffle = False,
                            use_probas = True,
                            cv = 5,
                            meta_classifier = lr)

In [96]:
sclf.fit(X_train, y_train)

StackingCVClassifier(classifiers=[XGBClassifier(base_score=0.5,
                                                booster='gbtree', colsample=1,
                                                colsample_bylevel=1,
                                                colsample_bynode=1,
                                                colsample_bytree=1, gamma=0,
                                                learning_rate=0.1,
                                                max_delta_step=5, max_depth=25,
                                                min_child_weight=0.0001,
                                                missing=None, n_estimators=100,
                                                n_jobs=1, nthread=None,
                                                objective='binary:logistic',
                                                random_state=0, reg_alpha=0.1,
                                                reg_lambda=...
                                                    

In [97]:
pred=sclf.predict(X)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
tn, fp, fn, tp = confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
cm=confusion_matrix(df['SURVIVAL_STATUS'], pred,labels=[0,1]).ravel()
total=sum(cm)
accuracy=(tp+tn)/(tp+tn+fn+fp)
sensitivity = tp/(tp+fn)
specificity = tn/(tn+fp)
print('Specificity : ', specificity)
print('Sensitivity : ', sensitivity )
print ('Accuracy : ', accuracy)
print('Confusion Matrix : \n', cm)

Specificity :  0.8235294117647058
Sensitivity :  0.9938650306748467
Accuracy :  0.9708222811671088
Confusion Matrix : 
 [ 42   9   2 324]


In [98]:
roc_auc_score(df['SURVIVAL_STATUS'], pred)


0.9086972212197763